# Note: This storageclass assumes using AWS EKS, with proper roles configured.
# This is for an EBS volume, not EFS or local, etc. 
# IAM Docs @ https://docs.aws.amazon.com/eks/latest/userguide/ebs-csi.html
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: gp2
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  fsType: ext4 
reclaimPolicy: Retain
volumeBindingMode: Immediate

